/**
 * app/(chat)/api/agent/run/route.ts
 *
 * Authenticated browser-facing trigger for the `/agent [task]` slash command.
 *
 * Responsibilities:
 * 1. Validate session & inputs.
 * 2. Save the user message to the DB (idempotent via upsertMessages).
 * 3. Create an AgentTask row — this activates the existing 4 s polling loop
 *    in chat.tsx so the UI picks up progress messages automatically.
 * 4. Write the initial empty workflow-progress card to the chat.
 * 5. Trigger the Upstash Workflow via QStash.
 * 6. Return { taskId, workflowRunId } synchronously — the heavy work is async.
 *
 * Falls back gracefully if QStash is not configured (QSTASH_TOKEN missing).
 */

import { type NextRequest, NextResponse } from "next/server";
import { auth } from "@/app/(auth)/auth";
import {
  createAgentTask,
  getChatById,
  saveChat,
  saveMessages,
  updateAgentTask,
  upsertMessages,
} from "@/lib/db/queries";
import { generateUUID } from "@/lib/utils";
import {
  triggerAgentRunWorkflow,
  isWorkflowEnabled,
} from "@/lib/workflow/client";
import { upsertWorkflowProgress } from "@/lib/agent/workflow-progress.server";
import { makeRunningStep } from "@/lib/agent/workflow-progress";
import { DEFAULT_CHAT_MODEL } from "@/lib/ai/models";
import type { DBMessage } from "@/lib/db/schema";

export const maxDuration = 30;

export async function POST(req: NextRequest) {
  // ── Auth ───────────────────────────────────────────────────────────────────
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const userId = session.user.id;

  // ── Parse body ─────────────────────────────────────────────────────────────
  let body: {
    task?: string;
    chatId?: string;
    model?: string;
    userMessageId?: string; // pre-generated by browser for idempotency
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const {
    task,
    chatId,
    model = DEFAULT_CHAT_MODEL,
    userMessageId = generateUUID(),
  } = body;

  if (!task?.trim()) {
    return NextResponse.json({ error: "Missing task" }, { status: 400 });
  }
  if (!chatId) {
    return NextResponse.json({ error: "Missing chatId" }, { status: 400 });
  }

  const taskText = task.trim();
  const taskId = generateUUID();
  const startedAt = new Date().toISOString();

  // ── Ensure chat exists ─────────────────────────────────────────────────────
  const chat = await getChatById({ id: chatId });
  if (chat) {
    if (chat.userId !== userId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
  } else {
    await saveChat({
      id: chatId,
      userId,
      title: taskText.slice(0, 100),
      visibility: "private",
    });
  }

  // ── Persist user message ───────────────────────────────────────────────────
  // upsertMessages → onConflictDoNothing equivalent via idempotent userMessageId
  await saveMessages({
    messages: [
      {
        id: userMessageId,
        chatId,
        role: "user",
        parts: [{ type: "text", text: `/agent ${taskText}` }],
        attachments: [],
        createdAt: new Date(),
      } as DBMessage,
    ],
  });

  // ── Create AgentTask ───────────────────────────────────────────────────────
  // This row triggers the existing polling loop in chat.tsx (activeAgentTasks).
  await createAgentTask({
    id: taskId,
    userId,
    chatId,
    agentType: "agent_run",
    task: taskText,
  });

  // ── Guard: workflow must be configured ────────────────────────────────────
  if (!isWorkflowEnabled()) {
    await updateAgentTask({
      id: taskId,
      userId,
      status: "failed",
      result: { error: "QSTASH_TOKEN not configured — cannot run durable workflow." },
    });
    return NextResponse.json(
      { error: "Workflow not configured. Set QSTASH_TOKEN and BASE_URL." },
      { status: 503 },
    );
  }

  // ── Write initial progress card ────────────────────────────────────────────
  // We don't have a workflowRunId yet — use a placeholder so the card appears
  // immediately while QStash processes the trigger request.
  await upsertWorkflowProgress({
    chatId,
    taskId,
    workflowRunId: "pending",
    task: taskText,
    steps: [makeRunningStep(0, "recall-context", "Recalling relevant context")],
    overallStatus: "running",
    startedAt,
  });

  // ── Trigger Upstash Workflow ───────────────────────────────────────────────
  let workflowRunId = "unknown";
  try {
    const result = await triggerAgentRunWorkflow({
      taskId,
      userId,
      chatId,
      task: taskText,
      model,
      userMessageId,
    });

    if (!result) {
      throw new Error("triggerAgentRunWorkflow returned null");
    }

    workflowRunId = result.workflowRunId;

    // Back-fill the real workflowRunId into the progress card.
    await upsertWorkflowProgress({
      chatId,
      taskId,
      workflowRunId,
      task: taskText,
      steps: [makeRunningStep(0, "recall-context", "Recalling relevant context")],
      overallStatus: "running",
      startedAt,
    });
  } catch (err) {
    console.error("[AgentRun] Failed to trigger workflow:", err);
    await updateAgentTask({
      id: taskId,
      userId,
      status: "failed",
      result: { error: err instanceof Error ? err.message : "Workflow trigger failed" },
    });
    return NextResponse.json({ error: "Workflow trigger failed" }, { status: 500 });
  }

  return NextResponse.json({ taskId, workflowRunId });
}