/**
 * lib/agent/workflow-progress.ts
 *
 * Shared types, codec, and step-factory helpers for the /agent workflow.
 *
 * ⚠️  This file is imported by client components (message.tsx, workflow-step.tsx).
 *     Keep it free of server-only imports (no "server-only", no DB/postgres).
 *     DB helpers live in lib/agent/workflow-progress.server.ts.
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export type WorkflowStepStatus = "pending" | "running" | "completed" | "failed";

export type WorkflowStep = {
  /** 0-based index, stable across retries */
  stepIndex: number;
  /** Machine-readable step name matching the context.run() key */
  name: string;
  /** Human-readable label shown in the UI */
  label: string;
  status: WorkflowStepStatus;
  /** Name of the tool currently being called (during execute step) */
  currentTool?: string;
  /** Cumulative tool calls this step */
  toolCallCount?: number;
  /** Truncated output preview (≤ 300 chars) */
  output?: string;
  /** Error message if status === "failed" */
  error?: string;
  startedAt: string; // ISO-8601
  completedAt?: string; // ISO-8601
  durationMs?: number;
};

export type WorkflowOverallStatus = "running" | "completed" | "failed";

export type WorkflowProgress = {
  taskId: string;
  workflowRunId: string;
  /** Full task text as typed by the user */
  task: string;
  steps: WorkflowStep[];
  overallStatus: WorkflowOverallStatus;
  startedAt: string; // ISO-8601
  completedAt?: string; // ISO-8601
};

// ── Codec ─────────────────────────────────────────────────────────────────────

export const WORKFLOW_PROGRESS_PREFIX = "###WORKFLOW_PROGRESS###";

export function encodeWorkflowProgress(p: WorkflowProgress): string {
  return `${WORKFLOW_PROGRESS_PREFIX}${JSON.stringify(p)}`;
}

export function decodeWorkflowProgress(text: string): WorkflowProgress | null {
  const trimmed = text.trim();
  if (!trimmed.includes(WORKFLOW_PROGRESS_PREFIX)) return null;

  try {
    const parts = trimmed.split(WORKFLOW_PROGRESS_PREFIX);
    const jsonStr = parts[parts.length - 1];
    return JSON.parse(jsonStr) as WorkflowProgress;
  } catch {
    return null;
  }
}

// ── Deterministic message ID ──────────────────────────────────────────────────

/**
 * Returns the stable message ID used for the progress card.
 * Using `upsertMessages`, every write to this ID overwrites `parts` in place.
 *
 * We use `taskId` directly — it's already a UUID (generated by generateUUID()),
 * which satisfies the `uuid` column constraint on Message_v2.id.
 */
export function workflowProgressMessageId(taskId: string): string {
  return taskId;
}

// ── Step factory helpers (reduces boilerplate in the workflow file) ────────────

export function makeRunningStep(
  stepIndex: number,
  name: string,
  label: string,
): WorkflowStep {
  return {
    stepIndex,
    name,
    label,
    status: "running",
    startedAt: new Date().toISOString(),
  };
}

export function completeStep(
  step: WorkflowStep,
  opts: { output?: string; toolCallCount?: number } = {},
): WorkflowStep {
  const completedAt = new Date().toISOString();
  return {
    ...step,
    status: "completed",
    completedAt,
    durationMs: new Date(completedAt).getTime() - new Date(step.startedAt).getTime(),
    ...opts,
  };
}

export function failStep(step: WorkflowStep, error: string): WorkflowStep {
  const completedAt = new Date().toISOString();
  return {
    ...step,
    status: "failed",
    completedAt,
    durationMs: new Date(completedAt).getTime() - new Date(step.startedAt).getTime(),
    error,
  };
}